mybatis:
  mapper-locations: classpath:mapper/*.xml

spring:
  #thymeleaf模板引擎配置
  thymeleaf:
    #是否开启缓存，开发过程中建议关闭
    cache: false
    #编码，默认为UTF-8
    encoding: utf-8
    servlet:
      content-type: text/html

  #Redis配置  配置文件位置 RedisProperties.class
  redis:
    #Redis数据库索引（默认为0）
    database: 0
    #Redis服务器地址 默认为localhost
    host: localhost
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:

    #jedis 或者 lettuce
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0

